{% set name = "pymt_prms_groundwater" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/pymt-lab/{{ name }}
  git_rev: v{{ version }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - prms
    - prms_groundwater
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - prms
    - prms_groundwater

test:
  imports:
    - pymt_prms_groundwater

about:
  summary: Python package that wraps the PRMS Groundwater BMI.
  home: https://github.com/pymt-lab/pymt_prms_groundwater
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_prms_groundwater
